### ISSUE TITLE
重复注册会错误

### ISSUE THREAD

**Issue by ctocode** [imlinfly/webman-annotation#2]
RouteAnnotationHandle.php 中，假如

```php

Route::add(['GET', 'OPTIONS'], '/test2', [\app\controller\Index::class, 'index']);
Route::add(['POST', 'OPTIONS'], '/test2', [\app\controller\Index::class, 'index']);

```
会报错 
```php
FastRoute\BadRouteException: Cannot register two routes matching "/test2" for method "OPTIONS"
```

**Comment by imlinfly** [comment]
这两个路由的OPTIONS请求重复注册了就会报错的，这个是FastRoute包的机制。就算使用Webman内置的路由注册，重复注册路由也会报错。
![52@JNGESU70YL6Z@FY7B V](https://user-images.githubusercontent.com/45063822/204299470-cd2fa372-3ad3-4e8a-90d7-4396aedcac43.png)

![Z58KV~%RO3P6T2EUFYTEFKS](https://user-images.githubusercontent.com/45063822/204299492-83f3de70-8a56-4757-a629-04d948260607.png)

**Comment by imlinfly** [comment]
因为相同的路由下OPTIONS请求类型已经注册过了，重复注册是会报错的。这个是FastRoute路由的机制，就算使用Webman提供的路由注册，重复注册路由也会报错的。

![1O9NIO0}1{IC5X03K48F8TG](https://user-images.githubusercontent.com/45063822/204300851-b95c589f-4477-402f-aca8-5e383fd487c9.png)
![1O9NIO0}1{IC5X03K48F8TG](https://user-images.githubusercontent.com/45063822/204300913-45206fa6-dc50-49c3-9de6-f9453958e683.png)

**Comment by north521** [comment]
如果使用原生的路由注册，其他的比如验证器、中间件注解会无效
