### ISSUE TITLE
start.php start -d 启动时，fwrite(STDOUT,$message)报错

### ISSUE THREAD

**Issue by cool222** [imlinfly/webman-annotation#3]
当带 -d 启动时，
TypeError: fwrite(): supplied resource is not a valid stream resource in /xxx/vendor/linfly/annotation/src/Util/AnnotationUtil.php:158
#0 /annotation/src/Util/AnnotationUtil.php(158): fwrite()

难道是 -d 启动时，没有 STDOUT 可用？

**Comment by imlinfly** [comment]
是的，Workerman在部署模式启动时关闭了STDOUT，master版本已经修复这个问题了。
