### ISSUE TITLE
如果不使用路由注解，其他注解不会生效

### ISSUE THREAD

**Issue by north521** [imlinfly/webman-annotation#4]
当使用路由注解，验证注解有效，否则无效

**Comment by north521** [comment]
#[Route(path: '/abc')]
#[Validate(validate: User::class)]
public function abc(){
    return response('hello');
}
当我这样设置，验证器可以生效，当去掉路由注解#[Route(path: '/abc')]后，验证器则不生效

**Comment by imlinfly** [comment]
你好，
注解中间件、验证器都需要配合注解路由一起使用，因为注解中间件、验证器都是调用webman原生的路由注册后再调用的Webman\Route::middleware方法注册的。所以没有使用注解路由，就无法注册原生的路由中间件，因此注解中间件、验证器就无法使用。

**Comment by imlinfly** [comment]
注解中间件的原理如下
```php
$rule = Route::get('/test', [app\controller\TestController::class, 'index']);
$rule->middleware(app\middleware\TestMiddleware::class);
```

只有使用了注解路由后才能使用注解中间件。

**Comment by north521** [comment]
> 

怎么可以使用原生路由来配合中间件、验证器来一块使用呢？

**Comment by imlinfly** [comment]
目前没办法让原生路由来配合注解中间件、验证器来一块使用，让我想想，有没有其他方法能实现。

**Comment by north521** [comment]
好的，非常感谢

**Comment by imlinfly** [comment]
你好，master分支最新的代码已经实现了绑定原生路由注解的功能，使用方法参见 [绑定原生路由](https://github.com/imlinfly/webman-annotation#%E7%BB%91%E5%AE%9A%E5%8E%9F%E7%94%9F%E8%B7%AF%E7%94%B1)

**Comment by north521** [comment]
版本没更新？还是1.0.6

**Comment by imlinfly** [comment]
> 版本没更新？还是1.0.6

稍等马上更新，其实你可以直接拉master的包。

**Comment by north521** [comment]
我直接下载复制，可以用，谢谢

**Comment by imlinfly** [comment]
> 我直接下载复制，可以用，谢谢

好的，1.0.7版本已经发布了
