### ISSUE TITLE
使用注解的依赖注入，修改config/container.php文件，\LinFly\FacadeContainer 没看到有这个类呀？

### ISSUE THREAD

**Issue by inccleo** [imlinfly/webman-annotation#5]

**Comment by imlinfly** [comment]
稍等，我这边测试一下，方便提供下你使用的哪个版本吗？

**Comment by inccleo** [comment]
> 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？

1.0

**Comment by imlinfly** [comment]
在根目录下`composer.lock`文件中可以查看详细的`linfly/annotation`包版本，依赖注入从 `v1.0.7` 版本开始支持。
![image](https://user-images.githubusercontent.com/45063822/212642652-b777b648-6986-4eb7-a517-c7a4f401fcac.png)

**Comment by imlinfly** [comment]
> > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> 
> 1.0

我这边拉取最新的webman框架代码和最新的`linfly/annotation`包测试没有发现复现你这种问题，建议你那边更新一下`linfly/annotation`包。
完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)

**Comment by imlinfly** [comment]
> > > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> > 
> > 
> > 1.0
> 
> 我这边拉取最新的webman框架代码和最新的`linfly/annotation`包，测试没有复现你这种问题，建议你那边更新一下`linfly/annotation`包。 完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)

**Comment by imlinfly** [comment]
> > > > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> > > 
> > > 
> > > 1.0
> > 
> > 
> > 我这边拉取最新的webman框架代码和最新的`linfly/annotation`包，测试没有复现你这种问题，建议你那边更新一下`linfly/annotation`包。 
完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)

**Comment by inccleo** [comment]
> > > > > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> > > > 
> > > > 
> > > > 1.0
> > > 
> > > 
> > > 我这边拉取最新的webman框架代码和最新的`linfly/annotation`包，测试没有复现你这种问题，建议你那边更新一下`linfly/annotation`包。
> > > 完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)

但是我安装不上1.07的版本 我是php8.0 webman 1.4.10

**Comment by imlinfly** [comment]
> > > > > > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> > > > > 
> > > > > 
> > > > > 1.0
> > > > 
> > > > 
> > > > 我这边拉取最新的webman框架代码和最新的`linfly/annotation`包，测试没有复现你这种问题，建议你那边更新一下`linfly/annotation`包。
> > > > 完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)
> 
> 但是我安装不上1.07的版本 我是php8.0 webman 1.4.10

麻烦提供一下composer安装时提示的信息呢

**Comment by inccleo** [comment]
> > > > > > > 稍等，我这边测试一下，方便提供下你使用的哪个版本吗？
> > > > > > 
> > > > > > 
> > > > > > 1.0
> > > > > 
> > > > > 
> > > > > 我这边拉取最新的webman框架代码和最新的`linfly/annotation`包，测试没有复现你这种问题，建议你那边更新一下`linfly/annotation`包。
> > > > > 完整的测试代码：[test_code.zip](https://www.eyabc.cn/share/issues/webman-annotation/5/test_code.zip)
> > 
> > 
> > 但是我安装不上1.07的版本 我是php8.0 webman 1.4.10
> 
> 麻烦提供一下composer安装时提示的信息呢

 Problem 1
    - Root composer.json requires linfly/annotation 1.0.7 -> satisfiable by linfly/annotation[1.0.7].
    - linfly/annotation 1.0.7 requires linfly/container ^1.0 -> found linfly/container[dev-master] but it does not match the constraint.

**Comment by imlinfly** [comment]
看样子是找不到` linfly/container ^1.0`这个版本的包，你的composer使用的是国内源吗？如果是尝试切换到官方源试试。

**Comment by inccleo** [comment]
> 看样子是找不到` linfly/container ^1.0`这个版本的包，你的composer使用的是国内源吗？如果是尝试切换到官方源试试。

切换到华为云安装上了，谢谢您的回复
