### ISSUE TITLE
中间件可以传参吗

### ISSUE THREAD

**Issue by north521** [imlinfly/webman-annotation#6]

**Comment by imlinfly** [comment]
你好，
你指的是`get` `post`参数吗？

**Comment by imlinfly** [comment]
中间件目前只支持以下三个参数：
```php
/**
 * @Controller(prefix="/api")
 * 
 * 
 * 注解中间件 需要和注解路由一起使用
 * @param string|array $middlewares 路由中间件 支持多个中间件
 * @param array $only 指定需要走中间件的方法, 不指定则全部走中间件, 与except互斥 只支持在控制器上使用
 * @param array $except 指定不需要走中间件的方法, 不指定则全部走中间件, 与only互斥 只支持在控制器上使用
 * 
 * @Middleware(middlewares=AuthMiddleware::class, only={"get"})
 */
// PHP8注解方式
#[Middleware(middlewares=AuthMiddleware::class, only: ['get'])]
```

**Comment by north521** [comment]
类似于这种官方的，可以传参数

路由配置 config/route.php

<?php
use support\Request;
use Webman\Route;

Route::any('/test', [app\controller\IndexController::class, 'index'])->setParams(['some_key' =>'some value']);

其实我本意是想实现一个类似于hyperf切面注解来完成某些用户校验，比如：用户是否被禁言，控制用户发表次数等等，如果中间传可以参，也可以实现

**Comment by imlinfly** [comment]
> 类似于这种官方的，可以传参数
> 
> 路由配置 config/route.php
> 
> setParams(['some_key' =>'some value']); 其实我本意是想实现一个类似于hyperf切面注解来完成某些用户校验，比如：用户是否被禁言，控制用户发表次数等等，如果中间传可以参，也可以实现

使用注解路由可以传参，参数如下：
```php
/**
 * 注解路由
 * @param string|array $path 路由路径 使用"/"开始则忽略控制器分组路径
 * @param array $methods 请求方法 例：GET 或 ['GET', 'POST']，默认为所有方法
 * @param string $name 路由名称 用于生成url的别名
 * @param array $params 路由参数
 * 
 * @Route(path="get", methods="get")
 */
 // PHP8注解方式
 #[Route(path: 'get', methods: 'get')]
 public function get()
 {
     return 'get';
 }
```

**Comment by north521** [comment]
我现在是用这种方法实现：Route::get('/test1.api',[TestController::class,'test1'])->setParams(['ttl'=>1000]);
来控制参数，实现用户限制

**Comment by north521** [comment]
Route::get('/test1.api',[TestController::class,'test1'])->middleware(Cacheable::class)->setParams(['ttl'=>300])

刚发错了

**Comment by imlinfly** [comment]
> Route::get('/test1.api',[TestController::class,'test1'])->middleware(Cacheable::class)->setParams(['ttl'=>300])
> 
> 刚发错了

如果用到了注解路由是可以通过params参数传参的，格式跟webman路由的setParams方法一样。
如果用到了绑定原生路由则只能在定义原生路由的地方设置参数。

**Comment by imlinfly** [comment]
你好，刚发布的1.0.8版本中增加了绑定原生路由注解时，支持传递`params`和`name`参数
```php
/**
  * 绑定原生路由注解参数说明
  * @param array $params 路由参数
  * @param string $name 路由名称 用于生成url的别名
  */
  #[BindRoute(params: ['info' => 'test_bind_route'], name: 'test_bind_route')]
```
