### ISSUE TITLE
2.0以上的版本 好像文档没有更新

### ISSUE THREAD

**Issue by Jzh-thub** [imlinfly/webman-annotation#8]

**Comment by imlinfly** [comment]
这段时间太忙了 2.0还没有发布正式版本。
2.0主要是废弃了PHP8之前的“注释解析”，只支持PHP8原生注解。
调整了注解类的目录结构，注解路由“Route”、"GetRoute"重命名为“RequestMapping”、“GetMapping”、... 
其他的使用方法和1.x版本一致。
