### ISSUE TITLE
同时使用控制器注解和注解路由 导致bug

### ISSUE THREAD

**Issue by Jzh-thub** [imlinfly/webman-annotation#9]
会产生2个路由 一个 prefix+path 一个path的路由
<img width="793" alt="image" src="https://github.com/imlinfly/webman-annotation/assets/74651570/c9d0909d-6018-471d-a90c-164c2e02d9da">

**Comment by imlinfly** [comment]
控制器输出的内容是从哪里打印的呢

**Comment by Jzh-thub** [comment]
$rows = [];
        foreach (\Webman\Route::getRoutes() as $route) {
            foreach ($route->getMethods() as $method) {
                $cb = $route->getCallback();
                $cb = $cb instanceof \Closure ? 'Closure' : (is_array($cb) ? json_encode($cb) : var_export($cb, 1));
                $rows[] = [$route->getPath(), $method, $cb, json_encode($route->getMiddleware() ?: null), $route->getName()];
            }
        }

        print_r($rows);

**Comment by Jzh-thub** [comment]
控制访问后打印的

**Comment by imlinfly** [comment]
麻烦使用`composer info`命令看一下`linfly/annotation`包的版本号，我这边刚拉取的webman框架使用的linfly/annotation:1.0.11版本没有复现这个问题。

**Comment by Jzh-thub** [comment]
好像是我这边 重复加载导致的，已排查了。
